apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ap2-v1
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-sample
  template:
    metadata:
      labels:
        app: nginx-sample
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
